#!/bin/bash

# Script to help setup GitHub Secrets for Render deployment
# Run this script to get the commands needed to set up GitHub Secrets

echo "=== GitHub Secrets Setup for Render Deployment ==="
echo ""
echo "Please run the following commands to set up your GitHub Secrets:"
echo ""
echo "# Render Configuration"
echo "gh secret set RENDER_API_KEY --body 'your_render_api_key_here'"
echo "gh secret set RENDER_SERVICE_ID_V2 --body 'your_bot_service_id_here'"
echo "gh secret set RENDER_ADMIN_SERVICE_ID_V2 --body 'your_admin_service_id_here'"
echo ""
echo "# WhatsApp Configuration"
echo "gh secret set WHATSAPP_API_URL --body 'https://gowa-gh2m5ozca4dh.wortel.sumopod.my.id'"
echo "gh secret set WHATSAPP_USERNAME --body '0iK2Kv4m'"
echo "gh secret set WHATSAPP_PASSWORD --body 'QUWlXsiaTHFBoSBM0WPtzRdQ'"
echo "gh secret set WHATSAPP_WEBHOOK_TOKEN --body 'test_webhook_token_123'"
echo ""
echo "# Supabase Configuration"
echo "gh secret set SUPABASE_URL --body 'https://cwixdvfffqjeyhbvxsph.supabase.co'"
echo "gh secret set SUPABASE_ANON_KEY --body 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN3aXhkdmZmZnFqZXloYnZ4c3BoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcyNzkzNTEsImV4cCI6MjA3Mjg1NTM1MX0.m6VyCTNUuxEsSbDb7v0fem_wx7rlTjiyrg1Yoym04x8'"
echo "gh secret set SUPABASE_SERVICE_ROLE_KEY --body 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN3aXhkdmZmZnFqZXloYnZ4c3BoIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc1NzI3OTM1MSwiZXhwIjoyMDcyODU1MzUxfQ.IJSWJBcQLtnctjVArr9UeN-bcd_gDzUlUXKqIHOoeMA'"
echo ""
echo "# AI Configuration"
echo "gh secret set GEMINI_API_KEY --body 'AIzaSyAAds8Bj0-0xY7n9ZEk4jYeCFdYfYzVZmk'"
echo ""
echo "=== Alternative: Manual Setup ==="
echo "You can also set these secrets manually in GitHub:"
echo "1. Go to your repository on GitHub"
echo "2. Click on Settings > Secrets and variables > Actions"
echo "3. Add each secret with the corresponding value"
echo ""
echo "=== Render Dashboard Setup ==="
echo "Make sure to also set these environment variables in your Render dashboard:"
echo "1. Go to your Render service dashboard"
echo "2. Navigate to Environment tab"
echo "3. Add all the environment variables from env.production.secure"
echo ""
