#!/bin/bash

# Script to help setup environment variables in Render dashboard
# This script provides the commands and values needed

echo "=== Render Environment Variables Setup ==="
echo ""
echo "Please add these environment variables in your Render dashboard:"
echo ""
echo "=== BOT SERVER ENVIRONMENT VARIABLES ==="
echo "Service: Bot Server (whatsapp-bot-88061)"
echo ""
echo "NODE_ENV=production"
echo "PORT=3000"
echo "LOG_LEVEL=info"
echo "WHATSAPP_API_URL=https://gowa-gh2m5ozca4dh.wortel.sumopod.my.id"
echo "WHATSAPP_USERNAME=0iK2Kv4m"
echo "WHATSAPP_PASSWORD=QUWlXsiaTHFBoSBM0WPtzRdQ"
echo "WHATSAPP_WEBHOOK_TOKEN=test_webhook_token_123"
echo "SUPABASE_URL=https://cwixdvfffqjeyhbvxsph.supabase.co"
echo "SUPABASE_ANON_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN3aXhkdmZmZnFqZXloYnZ4c3BoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcyNzkzNTEsImV4cCI6MjA3Mjg1NTM1MX0.m6VyCTNUuxEsSbDb7v0fem_wx7rlTjiyrg1Yoym04x8"
echo "SUPABASE_SERVICE_ROLE_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN3aXhkdmZmZnFqZXloYnZ4c3BoIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc1NzI3OTM1MSwiZXhwIjoyMDcyODU1MzUxfQ.IJSWJBcQLtnctjVArr9UeN-bcd_gDzUlUXKqIHOoeMA"
echo "GEMINI_API_KEY=AIzaSyAAds8Bj0-0xY7n9ZEk4jYeCFdYfYzVZmk"
echo ""
echo "=== ADMIN WEB ENVIRONMENT VARIABLES ==="
echo "Service: Admin Web (whatsapp-admin-web)"
echo ""
echo "VITE_SUPABASE_URL=https://cwixdvfffqjeyhbvxsph.supabase.co"
echo "VITE_SUPABASE_ANON_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN3aXhkdmZmZnFqZXloYnZ4c3BoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcyNzkzNTEsImV4cCI6MjA3Mjg1NTM1MX0.m6VyCTNUuxEsSbDb7v0fem_wx7rlTjiyrg1Yoym04x8"
echo "VITE_APP_NAME=WhatsApp Template Admin"
echo "VITE_APP_VERSION=1.0.0"
echo ""
echo "=== HOW TO ADD ENVIRONMENT VARIABLES ==="
echo "1. Go to https://dashboard.render.com"
echo "2. Click on your service"
echo "3. Go to Environment tab"
echo "4. Click 'Add Environment Variable'"
echo "5. Add each variable with its value"
echo "6. Click 'Save Changes'"
echo ""
echo "=== IMPORTANT NOTES ==="
echo "- Make sure to add ALL variables for each service"
echo "- Double-check the values before saving"
echo "- After adding variables, redeploy the service"
echo ""
