services:
  - type: web
    name: whatsapp-bot-server
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: WHATSAPP_API_URL
        sync: false
      - key: WHATSAPP_USERNAME
        sync: false
      - key: WHATSAPP_PASSWORD
        sync: false
      - key: WHATSAPP_WEBHOOK_TOKEN
        sync: false
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_SERVICE_ROLE_KEY
        sync: false
      - key: LOG_LEVEL
        value: info

